gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me           \n"
	.string "           Birch.\p"
	
@	.string "But everyone calls me the Pokémon\n"
@	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
@	.string "This world is widely inhabited by\n"
@	.string "creatures known as Pokémon.\p"
@	.string "We humans live alongside Pokémon,\n"
@	.string "at times as friendly playmates, and\l"
@	.string "at times as cooperative workmates.\p"
@	.string "And sometimes, we band together\n"
@	.string "and battle others like us.\p"
@	.string "But despite our closeness, we don't\n"
@	.string "know everything about Pokémon.\p"
@	.string "In fact, there are many, many\n"
@	.string "secrets surrounding Pokémon.\p"
@	.string "To unravel Pokémon mysteries,\n"
@	.string "I've been undertaking research.\l"
@	.string "That's what I do.\p"
	
	.string "Each Pokémon species has innate\n"
	.string "characteristics that set them apart\n"
	.string "from each other.\p"
	.string "Pokémon Trainers raise Pokémon to\n"
	.string "bring out their latent potential.\p"
	.string "I'm here to help new Trainers get\n"
	.string "started on the right foot.\p"
	.string "The Hoenn region has changed a lot\n"
	.string "in recent years, so I hope\n"
	.string "you'll take the time to explore.\p"
	.string "Even after all this time, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "That just means there's plenty\n"
	.string "of opportunity for you to leave\n"
	.string "your mark on the world!\p"
	
	.string "$"

gText_Birch_AndYouAre::
	.string "Let's start with your profile.$"

gText_Birch_BoyOrGirl::
	.string "Are you a BODY TYPE A?\n"
	.string "Or are you a BODY TYPE B?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} from the Littleroot\n"
	.string "District of Petalburg City.\l"
	.string "Thank you!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Pokémon lab.\p"
	.string "$"
